//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using TrainApp.Models;

    public partial class TrainAppEntities : DbContext
    {
        public TrainAppEntities()
            : base(@"Data Source=IBRAHIM;Initial Catalog=TrainApplastlast;User ID=sa;Password=iti")
        {

        }

        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TrainTrip>()
                .HasOptional(s => s.TrainPostObj)
                .WithRequired(j => j.TrainTripObj);

            modelBuilder.Entity<TrainType>()
                .HasOptional(a => a.TrainTripObj)
                .WithRequired(ab => ab.TrainTypeObj);
        }

       

        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<station> station { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<TrainPost> TrainPost { get; set; }
        public virtual DbSet<CommentsOntrain> CommentsOntrain { get; set; }
        public virtual DbSet<TrainTrip> TrainTrip { get; set; }
        public virtual DbSet<TrainType> TrainType { get; set; }

    }
}
